/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oops;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author tulaib pc
 */
public class addMoney extends javax.swing.JFrame {

    int money;
    String userId;
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public addMoney() {
        initComponents();
    }
    public addMoney(String userId,int money){
        this.userId=userId;
        this.money=money;
        initComponents();
        conn=signup.ConnectDb();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("add money");
        setMinimumSize(new java.awt.Dimension(500, 222));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("YOUR CURRENT BALANCE IS ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText(Integer.toString(money));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("ENTER THE AMOUNT YOU WANT TO ADD IN YOUR WALLET:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 155, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        JOptionPane.showMessageDialog(null, "no money has been added");
        new loginbut(userId,money).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            try{if(Integer.parseInt(jTextField5.getText())<=0){
                JOptionPane.showMessageDialog(null, "Please select a valid amount");
            }
            else{   
                money+=Integer.parseInt(jTextField5.getText());
                try{
                String sql="UPDATE userinfo set "
                        + ""+"money='"+money+"'" + 
                        "where userId='"+userId+"'";
                pst=conn.prepareStatement(sql);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"money added sucessfully!!");
                setVisible(false); 
                new loginbut(userId,money).setVisible(true);           
                }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                }
            }}catch(NumberFormatException ne){
                JOptionPane.showMessageDialog(null,"Please enter valid data");
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
